/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as RegisterRestaurantRouteImport } from './routes/register-restaurant'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoyaltyRouteImport } from './routes/admin.loyalty'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTablesRouteImport } from './routes/admin.tables'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthReactivateRouteImport } from './routes/auth.reactivate'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as FeedbackOrderIdRouteImport } from './routes/feedback.$orderId'
import { Route as TableQrTokenRouteImport } from './routes/table.$qrToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRestaurantRoute = RegisterRestaurantRouteImport.update({
  id: '/register-restaurant',
  path: '/register-restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTablesRoute = AdminTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReactivateRoute = AuthReactivateRouteImport.update({
  id: '/auth/reactivate',
  path: '/auth/reactivate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackOrderIdRoute = FeedbackOrderIdRouteImport.update({
  id: '/feedback/$orderId',
  path: '/feedback/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const TableQrTokenRoute = TableQrTokenRouteImport.update({
  id: '/table/$qrToken',
  path: '/table/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/register-restaurant': typeof RegisterRestaurantRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tables': typeof AdminTablesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reactivate': typeof AuthReactivateRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/feedback/$orderId': typeof FeedbackOrderIdRoute
  '/table/$qrToken': typeof TableQrTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/register-restaurant': typeof RegisterRestaurantRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tables': typeof AdminTablesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reactivate': typeof AuthReactivateRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/feedback/$orderId': typeof FeedbackOrderIdRoute
  '/table/$qrToken': typeof TableQrTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/register-restaurant': typeof RegisterRestaurantRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tables': typeof AdminTablesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reactivate': typeof AuthReactivateRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/feedback/$orderId': typeof FeedbackOrderIdRoute
  '/table/$qrToken': typeof TableQrTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/register-restaurant'
    | '/profile'
    | '/admin/branding'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/loyalty'
    | '/admin/menu'
    | '/admin/settings'
    | '/admin/tables'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/reactivate'
    | '/auth/verify'
    | '/feedback/$orderId'
    | '/table/$qrToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/register-restaurant'
    | '/profile'
    | '/admin/branding'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/loyalty'
    | '/admin/menu'
    | '/admin/settings'
    | '/admin/tables'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/reactivate'
    | '/auth/verify'
    | '/feedback/$orderId'
    | '/table/$qrToken'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/checkout'
    | '/register-restaurant'
    | '/_authenticated/profile'
    | '/admin/branding'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/loyalty'
    | '/admin/menu'
    | '/admin/settings'
    | '/admin/tables'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/reactivate'
    | '/auth/verify'
    | '/feedback/$orderId'
    | '/table/$qrToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  RegisterRestaurantRoute: typeof RegisterRestaurantRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthReactivateRoute: typeof AuthReactivateRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  FeedbackOrderIdRoute: typeof FeedbackOrderIdRoute
  TableQrTokenRoute: typeof TableQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-restaurant': {
      id: '/register-restaurant'
      path: '/register-restaurant'
      fullPath: '/register-restaurant'
      preLoaderRoute: typeof RegisterRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tables': {
      id: '/admin/tables'
      path: '/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AdminTablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reactivate': {
      id: '/auth/reactivate'
      path: '/auth/reactivate'
      fullPath: '/auth/reactivate'
      preLoaderRoute: typeof AuthReactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$orderId': {
      id: '/feedback/$orderId'
      path: '/feedback/$orderId'
      fullPath: '/feedback/$orderId'
      preLoaderRoute: typeof FeedbackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$qrToken': {
      id: '/table/$qrToken'
      path: '/table/$qrToken'
      fullPath: '/table/$qrToken'
      preLoaderRoute: typeof TableQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTablesRoute: typeof AdminTablesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTablesRoute: AdminTablesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  RegisterRestaurantRoute: RegisterRestaurantRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthReactivateRoute: AuthReactivateRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  FeedbackOrderIdRoute: FeedbackOrderIdRoute,
  TableQrTokenRoute: TableQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
